[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "cd next-frontend && npm install"

[phases.build]
cmd = "cd next-frontend && npm run build"

[start]
cmd = "cd next-frontend && NODE_ENV=production npm start"
